import json

# 元データ（Pythonの辞書リスト形式）
data = [
    { "name": "琉球大学アメリカンフットボール部", "day": "未記載", "location": "サッカー・ラグビー場", "detail": "アメリカンフットボールの公式部活動", "sns": "https://www.instagram.com/ryukyu.stingrays?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉大アルティメットサークルRyuul", "day": "火曜日、木曜日 ・17:00〜日没", "location": "未記載", "detail": "アルティメット（フライングディスク競技）のサークル", "sns": "https://www.instagram.com/ryu_dai_ult?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学全学ウィンドサーフィン部", "day": "未記載", "location": "未記載", "detail": "ウィンドサーフィン活動を行う部", "sns": "https://www.instagram.com/windsurfing52_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉大Surf Team", "day": "未記載", "location": "未記載", "detail": "サーフィン活動サークル", "sns": "https://www.instagram.com/rust_1981?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学ライフセービング部", "day": "未記載", "location": "未記載", "detail": "ライフセービング技術の習得・活動", "sns": "https://www.instagram.com/ryudai_lifesaving_club?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉大公認ダイビングサークルMARiN", "day": "毎週木曜日に部会、土曜日にダイビング", "location": "未記載", "detail": "スキューバダイビング活動", "sns": "https://www.instagram.com/divingcircle_marin?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "U.R.D.C.", "day": "未記載", "location": "未記載", "detail": "ダンス系のサークル（詳細不明）", "sns": "https://www.instagram.com/urdc_diving_club?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "クライミングサークル ゆんたくらいむ", "day": "未記載", "location": "未記載", "detail": "ボルダリング・クライミング活動", "sns": "未記載" },
    { "name": "琉球大学ツーリングチーム", "day": "未記載", "location": "未記載", "detail": "バイクツーリング愛好会", "sns": "未記載" },
    { "name": "琉球大学ゴルフ部", "day": "未記載", "location": "未記載", "detail": "ゴルフの練習・競技を行う部", "sns": "https://www.instagram.com/ryudai_golf?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉大サッカーサークル・フルオール", "day": "ストーリーやハイライトで公開", "location": "未記載", "detail": "サッカーサークル", "sns": "https://www.instagram.com/ryukyu.fruor?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学全学サッカー部", "day": "水金土(日)", "location": "東口グラウンド", "detail": "大学全体の公式サッカー部", "sns": "https://www.instagram.com/ryu.u_soc1966?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学フィギュアスケート部", "day": "未記載", "location": "未記載", "detail": "フィギュアスケート競技部", "sns": "https://www.instagram.com/ryudaifsc?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "すぽんちゅ", "day": "毎週(木)の19時30分~21時", "location": "第二体育館", "detail": "スポーツ交流系サークル", "sns": "https://www.instagram.com/ryukyu_suponchu_official?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "スポーツ同好会", "day": "月・木 18:00〜19:30", "location": "第二体育館", "detail": "多種目のスポーツを楽しむ同好会", "sns": "https://www.instagram.com/supodo_ryukyu?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学男子ソフトボール部", "day": "月水16:00〜18:00、土9:00〜12:00", "location": "琉大陸上競技場グラウンド", "detail": "男子ソフトボール競技部", "sns": "https://www.instagram.com/ryukyu_liners?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "体操部", "day": "火9:00〜11:00 土9:00〜11:00", "location": "第一体育館", "detail": "体操競技を行う部活動", "sns": "https://www.instagram.com/rad_daisuki_club?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学卓球部", "day": "（月、木）18:00~19:30（土）9:00〜11:00", "location": "未記載", "detail": "卓球の練習・大会参加を行う部", "sns": "https://www.instagram.com/ryudaitabletennis?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "R-family", "day": "月・木曜日 19:30〜21:00", "location": "第一体育館2階武道場", "detail": "ダンス系サークル（詳細不明）", "sns": "https://www.instagram.com/rfamily___?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "チアリーディング部Rays", "day": "(木)18:10〜 (土)9:00〜", "location": "第1体育館2階 武道場", "detail": "チアリーディングを行う公式部活動", "sns": "https://www.instagram.com/ryukyu.rays?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="},
    { "name": "琉球大学Belly dance circle \"moon light\"", "day": "毎週月曜日18:00-19:30", "location": "第一体育館2F武道場", "detail": "ベリーダンスを楽しむサークル", "sns": "https://www.instagram.com/ryudai_bellydance_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学ソフトテニス部", "day": "火・木 17時〜・土 10時〜", "location": "琉球大学テニスコート⁡", "detail": "ソフトテニスの練習・試合を行う部活動", "sns": "https://www.instagram.com/ryukyu_soft_tennis?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学全学硬式庭球部", "day": "毎週(火)(水)(金)17〜19時(土)10〜12時", "location": "琉球大学テニスコート", "detail": "硬式テニスの大学全体部活動", "sns": "https://www.instagram.com/uni.ryukyu_tennis?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学ウエイトトレーニングサークル", "day": "未記載", "location": "未記載", "detail": "筋力トレーニングやフィットネス活動", "sns": "未記載" },
    { "name": "琉球大学女子バスケットボール部", "day": "水曜日・土曜日", "location": "未記載", "detail": "女子バスケットボール競技部", "sns": "https://www.instagram.com/ryukyu.girls.basketball?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学男子バスケットボール部", "day": "月曜日・木曜日 18:00〜19:30土曜日 9:00〜11:00", "location": "第一体育館", "detail": "男子バスケットボール競技部", "sns": "https://www.instagram.com/ryukyu_univ_bsk?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "3×3バスケサークル", "day": "未記載", "location": "未記載", "detail": "3人制バスケットボールを楽しむサークル", "sns": "https://x.com/33bsk_ryu_univ" },
    { "name": "琉球大学男女バドミントン部", "day": "火曜日 19時半〜21時 水曜日18時〜19時半 土曜日11時〜13時", "location": "未記載", "detail": "バドミントンを楽しむサークル", "sns": "https://www.instagram.com/ryukyu.bad100?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "バレーサークル", "day": "未記載", "location": "未記載", "detail": "バレーボールを楽しむサークル", "sns": "未記載" },
    { "name": "バレー同好会", "day": "水曜日 19:30〜21:00 金曜日 16:30〜19:30", "location": "琉球大学第2体育館", "detail": "バレーボールを気軽に楽しむ同好会", "sns": "https://www.instagram.com/ryudai.volleyball?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学男子バレーボール部", "day": "月・金 17:00~19:30、土 9:00〜11:00", "location": "第二体育館", "detail": "男子バレーボールの公式部活動", "sns": "https://www.instagram.com/ryukyu_b_volleyball?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "ハンドボールサークル", "day": "毎週水曜 19時30分～21時", "location": "第一体育館", "detail": "ハンドボールを楽しむサークル", "sns": "https://www.instagram.com/ryukyuhando?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学男女ハンドボール部", "day": "月木金 19:30-21:00土 11:00-13:00", "location": "第一体育館", "detail": "男子ハンドボールの公式部活動", "sns": "https://www.instagram.com/ryukyuhandball?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "ガーボベルデ琉球", "day": "未記載", "location": "琉球大学 第1体育館", "detail": "フットサル・サッカー関連のチーム（詳細不明）", "sns": "https://www.instagram.com/gaboberude/?utm_source=ig_web_button_share_sheet" },
    { "name": "琉球大学躰道部", "day": "月・水 18:00〜19:30、金 19:30〜21:00、土 9:00〜13:00", "location": "未記載", "detail": "躰道を行う武道系部活動", "sns": "https://www.instagram.com/taidopple?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "柔道部", "day": "火曜 19時30分~21時 金曜 18時~19時30分", "location": "第一体育館2階武道場", "detail": "柔道の公式部活動", "sns": "https://www.instagram.com/ryudai.judo/?utm_source=ig_web_button_share_sheet" },
    { "name": "琉球大学合気道部", "day": "月・水19:00〜（外練） /19:30〜（琉大武道場）木（隔週）19:30〜（琉大武道場）土9:00〜（隔週で外部体育館）", "location": "未記載", "detail": "合気道の公式部活動", "sns": "https://www.instagram.com/ryudai_aiki?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学なぎなた部", "day": "未記載", "location": "未記載", "detail": "なぎなた競技を行う部活動", "sns": "未記載" },
    { "name": "琉球大学剣道部", "day": "水木土11:00〜13:00", "location": "第一体育館2階武道場", "detail": "剣道の稽古・大会参加を行う公式部活動", "sns": "https://www.instagram.com/ryu_daikendo_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学空手道部", "day": "火水木18時〜19:30", "location": "琉大第一体育館2階 武道場", "detail": "空手道の稽古・演武・大会参加を行う部活動", "sns": "https://www.instagram.com/ryudai_karate?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学全学弓道部", "day": "月水金 17:30~20:00", "location": "琉球大学弓道場", "detail": "弓道の練習・競技を行う大学全体の部活動", "sns": "https://www.instagram.com/ru_kyudo_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学居合道部", "day": "月曜日", "location": "未記載", "detail": "居合道の型・演武を行う部活動", "sns": "https://www.instagram.com/ryudai.iai?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学男子アイスホッケー部", "day": "毎週火・金・土", "location": "サザンヒルアイスアリーナ", "detail": "男子アイスホッケーの公式部活動", "sns": "https://x.com/ryudai_hockey" },
    { "name": "琉球大学女子アイスホッケー部", "day": "毎週火・金・土", "location": "未記載", "detail": "女子アイスホッケーの公式部活動", "sns": "https://x.com/ryudai_hockey" },
    { "name": "硬式野球部", "day": "未記載", "location": "未記載", "detail": "硬式野球の公式部活動", "sns": "https://www.instagram.com/ryukyu_bbc/" },
    { "name": "琉球大学ラグビー部", "day": "月・木 18:30～21:00土9:00 ～11:00", "location": "琉大東口グラウンド", "detail": "ラグビーの練習・試合を行う公式部活動", "sns": "https://www.instagram.com/ryukyurugby/?hl=ja" },
    { "name": "陸上競技部", "day": "月･水･木 17:00~19:00土 9:00~12:00", "location": "未記載", "detail": "陸上競技全般を行う部活動", "sns": "https://www.instagram.com/ryukyu_rikuzyou?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉大パントリー ぬちまーる", "day": "未記載", "location": "未記載", "detail": "学生支援を目的としたフードパントリー活動", "sns": "https://www.instagram.com/ryudai_pantry/" },
    { "name": "北球陽コミュニティ振興部", "day": "未記載", "location": "北球陽→千原キャンパスの球陽橋以北のエリア", "detail": "地域貢献や交流を目的としたサークル", "sns": "https://www.instagram.com/ryudai_northkyuyocomm/" },
    { "name": "RyunHug", "day": "未記載", "location": "未記載", "detail": "交流・支援系のサークル（詳細不明）", "sns": "https://www.instagram.com/ryunhug?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学モダンジャズオーケストラ", "day": "水曜日", "location": "未記載", "detail": "ビッグバンド形式でのジャズ演奏を行う音楽サークル", "sns": "https://www.instagram.com/ryudaimojo?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学管弦楽団", "day": "月・水・金曜 18:00〜21:00", "location": "サークル棟304・309", "detail": "クラシック音楽を中心に演奏するオーケストラ団体", "sns": "https://www.instagram.com/ryu_orche/" },
    { "name": "琉球大学吹奏楽部", "day": "火・木曜 18:00〜21:00 /土曜 13:00〜17:00", "location": "サークル棟311", "detail": "吹奏楽演奏、定期演奏会を行う部活動", "sns": "https://www.instagram.com/swing_chu?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "アカペラサークル うたゆん♪", "day": "木・土曜 18:00〜21:00", "location": "サークル棟205・208・213 /204・205・312", "detail": "アカペラ活動。初心者も歓迎", "sns": "https://www.instagram.com/ryudai_aca/" },
    { "name": "琉大ロック同好会", "day": "毎週土曜13:00〜", "location": "サークル棟306", "detail": "ロック音楽の演奏・セッションを楽しむ同好会", "sns": "https://www.instagram.com/ryudierock.rd6q/" },
    { "name": "琉球大学Jazz研究会", "day": "火・金曜 19:00〜21:00", "location": "サークル棟315", "detail": "ジャズ演奏を中心に活動する音楽サークル", "sns": "https://www.instagram.com/uryukyu_jazzken?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学科学ミステリーサークル", "day": "水曜日の14:00~", "location": "琉球大学理学部棟314号室", "detail": "科学に関する不思議や謎を研究・共有するサークル", "sns": "https://x.com/ryukyumystery" },
    { "name": "琉球大学Robotサークル", "day": "未記載", "location": "未記載", "detail": "ロボット製作・プログラミングを行うサークル", "sns": "https://www.instagram.com/robot_ryukyus?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "天文サークル スターダスト", "day": "未記載", "location": "未記載", "detail": "天体観測や宇宙に関する活動を行うサークル", "sns": "https://www.instagram.com/ryukyu_stardust?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "RYUKYU Education", "day": "未記載", "location": "未記載", "detail": "教育に関する研究・実践活動を行うサークル", "sns": "https://www.instagram.com/ryudai_global_education_center/" },
    { "name": "競技かるたサークル", "day": "金16:00〜19:30", "location": "教育学部棟522教室(書道室)", "detail": "競技かるたを楽しむサークル", "sns": "https://www.instagram.com/ryudai.karuta?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学自動車部", "day": "毎週金曜日18時", "location": "未記載", "detail": "自動車の整備・運転・研究を行う部活動", "sns": "https://www.instagram.com/u_r_a_c_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "社会科学研究会", "day": "未記載", "location": "未記載", "detail": "社会科学の研究・議論を行う研究会", "sns": "https://x.com/ryudaishyaken" },
    { "name": "琉球大学しままーいサークル", "day": "未記載", "location": "未記載", "detail": "地域散策・文化体験を目的としたサークル", "sns": "未記載" },
    { "name": "ゲームサークル", "day": "未記載", "location": "未記載", "detail": "テレビゲーム・ボードゲームなどを楽しむサークル", "sns": "未記載" },
    { "name": "琉大韓流クラブ", "day": "月２回", "location": "未記載", "detail": "K-POPや韓国文化に関心のある学生が集うクラブ", "sns": "https://www.instagram.com/ryudai_korea?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学マジックサークル", "day": "未記載", "location": "未記載", "detail": "マジック（手品）の練習・披露を行うサークル", "sns": "https://x.com/jim876421/status/1908098305189658976" },
    { "name": "琉球大学麻雀サークル", "day": "未記載", "location": "未記載", "detail": "麻雀を楽しむサークル", "sns": "https://www.instagram.com/ryukyu_mahjong_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "RyuMofu", "day": "水19-21時、土9-15時", "location": "サークルプレハブ1次棟 2F 9号室", "detail": "動物や癒やし系活動を行うサークル（詳細不明）", "sns": "https://www.instagram.com/ryumofu2023?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学ビリヤード部", "day": "隔週水曜日，金曜日", "location": "未記載", "detail": "ビリヤードを楽しむ部活動", "sns": "https://www.instagram.com/ryukyu.univ.billiards?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "ニューメディア", "day": "月〜土 9:00〜21:00(祝日除く)", "location": "サークル棟の106", "detail": "映像・デジタルメディアに関する活動", "sns": "https://x.com/SIN_NEOnewmedia?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" },
    { "name": "琉球大学スプラトゥーンサークル", "day": "水曜:21:00-23:00 土曜21:00-23:00", "location": "未記載", "detail": "ゲーム『スプラトゥーン』を楽しむサークル", "sns": "https://x.com/ryukyusplatoon?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" },
    { "name": "珈琲＆読書サークル", "day": "未記載", "location": "未記載", "detail": "コーヒーを飲みながら読書を楽しむサークル", "sns": "未記載" },
    { "name": "琉大レインボー", "day": "未記載", "location": "未記載", "detail": "LGBTQ+関連の交流や啓発を行うサークル", "sns": "https://www.instagram.com/ryudai_rainbow/" },
    { "name": "スタジオジャグリ", "day": "毎週火金18時～21時", "location": "橋の下ステージ", "detail": "演劇やパフォーマンスを行うサークル", "sns": "https://www.instagram.com/studiojuggle_0308?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "カイアルファ沖縄（琉大）", "day": "未記載", "location": "未記載", "detail": "キリスト教系の国際交流サークル", "sns": "https://www.instagram.com/chi_alpha_okinawa?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学学生新聞会", "day": "未記載", "location": "未記載", "detail": "大学のニュースや記事を発行する学生新聞", "sns": "未記載" },
    { "name": "琉球大学放送クラブ", "day": "未記載", "location": "未記載", "detail": "イベント司会・ラジオなどの放送活動を行うクラブ", "sns": "https://x.com/studio_rub?lang=ar-x-fm"},
    { "name": "琉球大学書道部", "day": "平日だいたい18:00~21:00", "location": "プレハブ3次棟2階10-1", "detail": "書道の練習と作品制作、展示活動を行う部活動", "sns": "https://www.instagram.com/ryudaishodou?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学文芸部", "day": "毎週月曜・ 木曜・金曜(18:00-)", "location": "未記載", "detail": "文学作品の創作や読書会を行うサークル", "sns": "https://x.com/ryukyu_bungei?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" },
    { "name": "琉球大学写真部", "day": "未記載", "location": "未記載", "detail": "写真撮影・展示を行うサークル", "sns": "https://www.instagram.com/ryukyuphoto2023?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "映画研究会", "day": "未記載", "location": "未記載", "detail": "映画鑑賞や自主制作を行うサークル", "sns": "https://www.instagram.com/ryudai_eiken/" },
    { "name": "美術部", "day": "水曜日の18:00～", "location": "未記載", "detail": "絵画・造形などの美術活動を行う部活動", "sns": "https://www.instagram.com/uryukyuart/" },
    { "name": "琉球大学漫画研究会（漫研）", "day": "金曜 18:30〜21:00", "location": "プレハブ1次棟 共用室12", "detail": "漫画制作・交流を行うサークル", "sns": "https://www.instagram.com/ryudai_manken?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学演劇部 劇団テトラ", "day": "毎日18:00〜", "location": "サークル棟302", "detail": "演劇公演・舞台練習を行うサークル", "sns": "https://www.instagram.com/gekidantetora?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "奇術研究会", "day": "未記載", "location": "未記載", "detail": "手品・マジックの研究と実演を行うサークル", "sns": "未記載" },
    { "name": "児童文化研究会", "day": "未記載", "location": "未記載", "detail": "子ども向けの文化活動や教育的イベントを行うサークル", "sns": "未記載" },
    { "name": "琉球大学環境サークル ゆいまーる", "day": "未記載", "location": "未記載", "detail": "環境保護活動や地域清掃などを行うサークル", "sns": "未記載" },
    { "name": "地域貢献サークル Ryunited", "day": "未記載", "location": "未記載", "detail": "地域清掃、学習支援、ボランティア活動を行うサークル", "sns": "https://www.instagram.com/ryunited22?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "ボランティアサークルHaisai", "day": "未記載", "location": "未記載", "detail": "地域や社会に向けたボランティア活動を行うサークル", "sns": "https://www.instagram.com/haisai_tanteidan/?hl=ja" },
    { "name": "メディア研究会", "day": "未記載", "location": "未記載", "detail": "テレビ・ラジオ・SNSなどメディアに関する研究活動", "sns": "未記載" },
    { "name": "国際交流サークル JICA x 琉大", "day": "未記載", "location": "未記載", "detail": "JICAと連携し、国際交流・協力活動を行うサークル", "sns": "https://www.instagram.com/jica.okinawa?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "国際交流サークル（一般）", "day": "未記載", "location": "未記載", "detail": "留学生との交流、異文化体験を目的としたサークル", "sns": "未記載" },
    { "name": "琉球大学模型部", "day": "未記載", "location": "未記載", "detail": "プラモデル・フィギュアなどの製作を行う部活動", "sns": "未記載" },
    { "name": "将棋サークル", "day": "毎週火木19〜21時", "location": "琉球大学サークル棟2号棟セミナー室", "detail": "将棋を楽しむサークル。初心者歓迎", "sns": "https://x.com/uryukyu_shogi_" },
    { "name": "囲碁サークル", "day": "毎週火木19〜21時", "location": "琉球大学サークル棟2号棟セミナー室", "detail": "囲碁を楽しむサークル", "sns": "未記載" },
    { "name": "eスポーツサークル", "day": "未記載", "location": "未記載", "detail": "オンラインゲーム・eスポーツを中心に活動するサークル", "sns": "https://x.com/lollor7?lang=ca" },
    { "name": "TRPGサークル", "day": "毎週土曜日", "location": "未記載", "detail": "テーブルトークRPGを楽しむサークル", "sns": "https://x.com/okinawa_de_trpg"},
    { "name": "琉球大学医学部ダイビング部", "day": "未記載", "location": "未記載", "detail": "ダイビング活動を行う医学部の部活動", "sns": "https://www.instagram.com/ryumedi_diving/" },
    { "name": "琉球大学医学部ボードセイリング部", "day": "未記載", "location": "未記載", "detail": "ボードセイリングを行う医学部の部活動", "sns": "https://www.instagram.com/ryumed_wind/?hl=ja" },
    { "name": "琉球大学医学部ゴルフ部", "day": "月&木20:00〜21:30 土18:30〜20:00", "location": "未記載", "detail": "ゴルフを行う医学部の部活動", "sns": "https://www.instagram.com/ryukyumedgolf/" },
    { "name": "琉球大学医学部サッカー部", "day": "月・水 18:40〜21:00 土 10:40〜13:00", "location": "・琉球大学千原キャンパスグラウンド・新都心公園人工芝・県総合運動公園人工芝", "detail": "サッカーを行う医学部の部活動", "sns": "https://www.instagram.com/ryukyu_soccer/" },
    { "name": "琉球大学医学部水泳部", "day": "水/土 17：30〜19：00", "location": "未記載", "detail": "水泳を行う医学部の部活動", "sns": "https://www.instagram.com/ryumed_swim/" },
    { "name": "琉球大学医学部卓球部", "day": "未記載", "location": "未記載", "detail": "卓球を行う医学部の部活動", "sns": "https://www.instagram.com/ryumed_tabletennis?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学医学部ダンス部", "day": "火曜日：19:00〜21:00 @武道場 金曜日：19:00〜21:00 @武道場 土曜日：19:00〜21:00 @環境の杜", "location": "未記載", "detail": "ダンスを行う医学部の部活動", "sns": "https://www.instagram.com/rmdc39/" },
    { "name": "琉球大学医学部男子硬式テニス部", "day": "月・水 17:00~19:00/土 15:00~17:00", "location": "未記載", "detail": "男子硬式テニスを行う医学部の部活動", "sns": "https://www.instagram.com/rmtc41?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学医学部女子硬式テニス部", "day": "月・水 17:00~19:00/土 15:00~17:00", "location": "未記載", "detail": "女子硬式テニスを行う医学部の部活動", "sns": "https://www.instagram.com/rmtc41?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学医学部バスケサークル同好会", "day": "木）16:30~18:30, （土）18:30~20:30", "location": "未記載", "detail": "バスケットボールを楽しむ医学部の同好会", "sns": "https://www.instagram.com/ryukyu_uni_bsk?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学医学部男子バレーボール部", "day": "火水金土の週4回", "location": "琉大医学部体育館", "detail": "男子バレーボールを行う医学部の部活動", "sns": "https://x.com/r_m_v_c" },
    { "name": "琉球大学医学部女子バレーボール部", "day": "火水金土の週4回", "location": "琉大医学部体育館", "detail": "女子バレーボールを行う医学部の部活動", "sns": "https://x.com/r_m_v_c" },
    { "name": "琉球大学医学部ハンドボール部", "day": "月曜日 19:00-21:00 @医学部体育館 木曜日 20:00-22:00 @外部の体育館 土曜日 16:30-18:30 @医学部体育館", "location": "未記載", "detail": "ハンドボールを行う医学部の部活動", "sns": "https://www.instagram.com/ryui_handball/?hl=ja" },
    { "name": "琉球大学医学部フットサル部", "day": "月木金", "location": "未記載", "detail": "フットサルを行う医学部の部活動", "sns": "https://www.instagram.com/salase.fut/" },
    { "name": "琉球大学医学部弓道部", "day": " 火曜,木曜17:00-20:00 土曜10:00-13:00", "location": "未記載", "detail": "弓道を行う医学部の部活動", "sns": "https://x.com/ryudaiikyu" },
    { "name": "琉球大学医学部剣道部", "day": "月木土", "location": "医学部体育館", "detail": "剣道を行う医学部の部活動", "sns": "https://www.instagram.com/ryudai_kendo/?hl=ja" },
    { "name": "琉球大学医学部空手道部", "day": "【月水】17:00-19:00 【土】12:30-14:30", "location": "未記載", "detail": "空手道を行う医学部の部活動", "sns": "https://www.instagram.com/ryumed_karate/" },
    { "name": "琉球大学医学部準硬式野球部", "day": "月水 17:00〜19:00 土 13:00〜17:00", "location": "未記載", "detail": "準硬式野球を行う医学部の部活動", "sns": "https://www.instagram.com/ryumed_baseball/" },
    { "name": "琉球大学医学部ラグビー部", "day": "月木18時30分〜21時 土8時30分〜11時", "location": "未記載", "detail": "ラグビーを行う医学部の部活動", "sns": "https://www.instagram.com/rmrfc?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉球大学医学部陸上競技部", "day": "月・水・木・土", "location": "西原競技場", "detail": "陸上競技を行う医学部の部活動", "sns": "https://www.instagram.com/ryumed.tandf?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "熱帯医学研究会", "day": "金曜17時〜 ", "location": "医学部がじゅまる会館3F和室", "detail": "熱帯医学に関する研究を行う会", "sns": "https://x.com/butanosuke2018" },
    { "name": "Off the Clock", "day": "未記載", "location": "未記載", "detail": "医学部の交流サークル（詳細不明）", "sns": "https://www.instagram.com/offtheclockryumed?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "メディカルプログラミングサークル", "day": "未記載", "location": "未記載", "detail": "プログラミングを学び医学に応用する研究サークル", "sns": "未記載" },
    { "name": "琉球大学地域医療研究会", "day": "木曜日18時10分", "location": "がしゅまる3階セミナー室", "detail": "地域医療に関する研究を行う会", "sns": "https://x.com/n_chiiken" },
    { "name": "中国医学研究会", "day": "毎週月曜日18:00", "location": "未記載", "detail": "中国医学に関する研究を行う会", "sns": "https://www.instagram.com/ryumed_chui?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" },
    { "name": "琉大医学部麻雀サークル", "day": "木・土", "location": "琉球大学西普天間キャンパス", "detail": "麻雀を楽しむ医学部のサークル", "sns": "https://x.com/ryumed_mahjong" },
    { "name": "琉球大学サークル ヨリドコロ", "day": "未記載", "location": "未記載", "detail": "学生の居場所づくりを目的とした交流サークル", "sns": "https://www.instagram.com/hospital_mind.okinawa?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" }
    ]

# JSONに整形して保存
with open("clubs.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("clubs.json を出力しました ✅")
